### ISSUE TITLE
Screen shot turn Black

### ISSUE THREAD

**Issue by C0D3rARCHIE** [bryal/DXGI_capture_lib#2]
this rarely works and the capture speed is all over. and most of the time the screen is 
black

**Comment by bryal** [comment]
Can you supply more detailed info? Works quite well for me.

**Comment by bryal** [comment]
Oh wow. I was going through my open issues and found this, and I just realized that when I commented in 2018, I was mistaking this repo for my other, similarly named, project [dxgcap-rs](https://github.com/bryal/dxgcap-rs), which does indeed work well, but I understand if this one doesn't. I wrote this software as a total C++ beginner, and beginner at programming in general, so I'm not surprised if it's buggy and doesn't work.

Anyhow, what I really came here to say is that I don't intend to maintain this project, and interested users should instead check out my (also slightly old and inactive at this point) Rust version of this project, dxgcap-rs, which I do intend to keep working at least for my own usecase.
